global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "kong"
    scrape_interval: 5s
    static_configs:
      - targets: ["kong:8001"]
    metrics_path: /metrics
